# Generated by Django 3.2.25 on 2024-06-28 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_auto_20240628_0934'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestLog',
        ),
    ]
